### ISSUE TITLE
is there a gencode.composite.collapsed.rds file for hg38?

### ISSUE THREAD

**Issue by pwaltman** [mskilab/gGnome#13]
Since I'm working with hg38, I'd love to have a version of the http://mskilab.com/gTrack/hg19//gencode.composite.collapsed.rds file for hg38.

If there isn't already one available, how can I create one for myself (that has the same fields and organization as the one you make available?

**Comment by mskilab** [comment]
Hi Peter - sorry for the late response but there is actually one available
at

http://mskilab.com/gTrack/hg38/gencode.composite.collapsed.rds
