### ISSUE TITLE
Event calling errors

### ISSUE THREAD

**Issue by willhooper** [mskilab/gGnome#16]
Hi,

I'm trying to call complex/simple events on my Jabba results. Most of the functions work, although a handful seem to fail. Is a dependency mismatch on my end?

**Versions:** R 3.6.1, GenomicRanges 1.34.0, gGnome 0.1, gUtils 0.2.0

Where x is loaded directly from jabba.simple.gg.rds:
```
> chromothripsis(x)
Error in gr.reduce(clgr, by = "cluster") :
  could not find function "gr.reduce"
```

```
> tic(x)
Error in H[!duplicated(as.matrix(H) > ZERO), ] :
  invalid or not-yet-implemented 'Matrix' subsetting
```

```
> qrp(x)
Error in H[!duplicated(as.matrix(H) > ZERO), ] :
  invalid or not-yet-implemented 'Matrix' subsetting
```

Thanks,
Will

**Comment by xtYao** [comment]
@willhooper is this resolved in the latest commit?
