### ISSUE TITLE
Customising appearance of gnome graph

### ISSUE THREAD

**Issue by alhafidzhamdan** [mskilab/gGnome#22]
Hi there- how can i switch the legend off ? 
Or how can i reposition it ?
Appreciate that this is a random question but i've been looking around and can't find how to do it.

![image](https://user-images.githubusercontent.com/53702866/104295860-df2e4800-54b8-11eb-83d8-f9c163d17d7e.png)

A

**Comment by mskilab** [comment]
Not sure if you got a reply here!  Sorry if not

You should be able to do plot(..., legend = FALSE) or set the track feature
gt$legend = FALSE.

The legend is coming from the gencode track, so set ge$legend = FALSE
before plotting.

**Comment by xtYao** [comment]
Will be addressed in the gTrack documentation. Thanks for bringing it up.
