### ISSUE TITLE
Out of Range Copy Number

### ISSUE THREAD

**Issue by mkinnaman** [mskilab/gGnome#70]
Hello!

When running the tool I sometimes will get complex rearrangements with CN calls like seen below which are not believable. How should these be interpreted - artifact? 

Thanks,
Michael

![image](https://user-images.githubusercontent.com/54551567/145291835-78ce68d8-d1ec-4251-857b-0d73d395ba87.png)

**Comment by ShaiberAlon** [comment]
Hi @mkinnaman , 
I agree, this definitely does not look right. Could you please provide more details regarding your workflow?
Thanks,
Alon

**Comment by mkinnaman** [comment]
Thanks Alon,

We use Jabba first using BRASS for copy number calls. Then ggnome to call events and visualize. Let me know if you needs any more details.

Thanks,
Michael

**Comment by ShaiberAlon** [comment]
And what did you use as read depth (or copy number) input?
